# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('filename', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('univ_code', models.CharField(choices=[('G', 'GIST'), ('J', 'Jeonnam')], max_length=1)),
            ],
        ),
    ]
