# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentcode', models.IntegerField()),
                ('univ_code', models.CharField(choices=[('G', 'GIST'), ('J', 'Jeonnam')], max_length=1)),
            ],
        ),
    ]
