# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_vote_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='photo',
            name='img',
            field=models.ImageField(default='photo/chick1.jpg', upload_to='photo/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='studentcode',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
