# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-19 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20171019_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
