# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171101_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Photo'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
    ]
