# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 18:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20171101_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0), size=3),
        ),
    ]
