# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_photo_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='score',
            new_name='score1',
        ),
        migrations.AddField(
            model_name='vote',
            name='score2',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='score3',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
    ]
